FROM golang:1.23 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy necessary files (go.mod and go.sum) to the container
COPY go.mod ./

# Download Go dependencies
RUN go mod download

# Copy the rest of the application source code
COPY . .

# Build the Go application
RUN go build -o main .

# Use a minimal image to run the built binary
FROM gcr.io/distroless/base
WORKDIR /app

# Copy the built binary and static files from the build stage
COPY --from=builder /app/main .
COPY --from=builder /app/static ./static

# Expose the application port
EXPOSE 8080

CMD ["./main"] 
